name: Build ISO

on:
  - push

jobs:
  build:
    name: Build ISO
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: uup download
        shell: powershell
        run: |
          cd uup
          ./uup_download_windows.cmd
          tree /F
